name: feature-workflow
on:
  push:
  workflow_dispatch:

jobs:
  feature_workflow:
    if: github.ref_name != 'main'
    uses: dharma0907/workflows/.github/workflows/nodejs-eks-feature.yaml@main
    with:
     project: "roboshop" 
     component: "catalogue" # this value been called in workflows


  
  main-workflow:
    runs-on:  ubuntu-latest
    steps:
      - name: main workflow
        run: echo "this runs when a commit comes to main branch"  